a = input('Digire algo:')
print('O tipo primitivo desse valor é', type(a))
print('So tem espaço?', a.isspace())
print('È um numero? ', a.isnumeric())
print('È alfabetico?', a.isalpha())
print('E alfanumerico?', a.isalnum())
print('Esta em maiusculas?', a.isupper())
print('Esta em minusculas?', a.islower())
print('Esta capitalizada?', a.istitle())
